### ISSUE TITLE
Can I get current Heart Rate from the watch into Home Assistant for automation?

### ISSUE THREAD

**Issue by CataCluj** [hatl/hasscontrol#27]
Hi,
I need to buy a watch/device that allows me to set automations based on current (not resting which is all I can get with FitBit; not rarely, which is what I get from Wear Os).
I'm considering buying a Garmin IF that were possible.
Thank you.

**Comment by BebeMischa** [comment]
as far as I know, it is not possible. There is a integration, which extracts all possible sensors, but current heart rate is not on the list...
https://github.com/cyberjunky/home-assistant-garmin_connect

**Comment by CataCluj** [comment]
Thank you.
I saw that; I was hoping it may just have been missed.
I was hoping to hear from somebody that actually has a Garmin watch and can confirm.
________________________________

**Comment by BebeMischa** [comment]
well, i do have two garmins and both do not expose that. ;-)

**Comment by CataCluj** [comment]
Thank you for letting me know.
What a shame!
No Garmin for me.
At least with Wear OS I do get something.
________________________________

**Comment by BebeMischa** [comment]
I would not be that resolute.

The Garmin app on the phone does it.

And the integration in HA (voluntarily work by @cyberjunky ) does expose more sensors, I will ever use. 

The quality of the watches themselves is a whole another level. I will not change that just because one missing function in HA... Question of different priorities. I use Garmin for activities, where I rely heavily on the watch it's reliability. No way, I will enter the deep Czech woods with any other watch ;-)

But hey, everyone choose, what matters for him ;-) Have fun with yours... ;-)

**Comment by hatl** [comment]
not planned as a feature for this app
