### ISSUE TITLE
Failed. Unknown Error Code -2

### ISSUE THREAD

**Issue by skorpi0n** [hatl/hasscontrol#9]
Hi
I cant get this widget to connect to my Home Assistant.
Every time I try, I get "Failed Unknown Error Code -2"
I've tried both long-lived token and normal login.
I'm using a Forerunner 935 with Home Assistant 2022.11.3

**Comment by nhallfast** [comment]
Hi,

I can confirm this as well. The old widget had stopped working and found this fork (great job in continuing support!)
I have a Vivoactive 3 Music with Home Assistant 2023.4.6
Nothing is found in logs on HA. Only visible error is on the watch: Failed Unknown Error Code -2.

I'm using the long lived token to log in.

Any help greatly appreciated!

**Comment by JohnBull-1975** [comment]
Just installed.
HA 2023.8.4
Android phone
Garmin FR 255m
Logging in with longe live access token (tried without first and phone opened an empty page where I couldn't login) 
Added two scenes.
"Failed unknown error Code -2" when I try to activate them.

**Comment by hatl** [comment]
are you using an https url or http?

**Comment by JohnBull-1975** [comment]
https

**Comment by JohnBull-1975** [comment]
wrong port number... missed a digit and now it works! Brilliant!

**Comment by andres-a-git** [comment]
I got the widget working nice with https and long live token. 
Then tried to add some not-supported entities like tracker. and person. to the Garmin group. 

After this action got the -2 error. Tried to uninstall the widget and make the group to old again but no luck. 
Scene looks to be adding normal but the entity list is not populated and I get the -2 error. 

Any ideas?

**Comment by hatl** [comment]
You could check how your group looks like via the REST API:

```sh
curl -s -X GET \
  -H "Authorization: Bearer YOUR_TOKEN" \
  https://home-assistant.hatl.network/api/states/group.garmin
```

**Comment by medsandor** [comment]
> You could check how your group looks like via the REST API:
> 
> curl -s -X GET \
>   -H "Authorization: Bearer YOUR_TOKEN" \
>   https://home-assistant.hatl.network/api/states/group.garmin

@hatl : I have a new widget install, configured a new long live access token, the connection works I think, but when trying to refresh group.garmin I also got the 

```
Failed
Unknown error 
code -2
```

What is interesting is that my Home Assistant reachable with a let's encrypt cert on 443 from the internet, and the hairpin NAT is working on my router, and this error only happens if I am connected with the mobile phone to the home wifi.
I have disabled the wifi, and from mobile internet the refresh succeeded, I can control the switch from my watch.

Also working if I login with wireguard to my home network using mobile internet, I can control the switch from my watch.

But if only native wifi at home, connection not working. 
This would mean the hairpin NAT not working but I am sure it is ok, because I can reach my external home assistand URL from any home pc connected to the home wifi or wired to the router.

**Comment by medsandor** [comment]
Hm, my outside URL works on desktop browsers, but not from the android phone where the Garmin connect app installed. If i enter the external home assistant URL, it says loading, but never loads

**Comment by hatl** [comment]
maybe your phone is using a different DNS server?

**Comment by medsandor** [comment]
DNS was ok, tried to set manually also in android for example to google's DNS servers, did not help.

Had a discussion with a chatbot, seems that the hairpin NAT handled differently in Android or I don't know the real cause.

Workaround was to add a DNS rewrite record and point my external domain name to the internal IP of Home Assistant. This way when the phone is on the wifi network it resolves to the local IP and the https connection and cert are still valid. And outside of home network it was already ok.
